### ISSUE TITLE
OK.Visa Integration Application

### ISSUE THREAD

**Issue by martind260** [it-at-m/digiwf-project#199]
### Summary
To externalize the integration of the ALW System OK.Visa in an asynchronous way, an extra app is needed, that receives query requests of a process instance via Kafka, forwards them to OK.Visa and routes the response back into the instance.

### Problem
Synchronous communication slows down the performance of the engine.

### Acceptance criteria

- [ ] The digiwf-alw-integration-starter is used
- [ ] Blueprint for the app is the it@M refenence architecture
- [ ] The App receives requests from a Kafka Topic, converts them to the ALW-specific format and forwards them to the external system
- [ ] The response of the external ALW-System is mapped by a configurable lookup table
- [ ] The mapped value is forwarded to the queue of DigiWF for message correlation
- [ ] The Kafka Topics and connection info for the ALW-System are configurable

### Status
- [ ] Reviewed in refinement

**Comment by xdoo** [comment]
@martind260 Do we implement version 1 or 2?

![image.png](https://images.zenhubusercontent.com/6220c3e56c0bae718921783b/1785bd46-99af-46e7-9f17-c65ad2fe14e0)

**Comment by martind260** [comment]
We dont have an extra EAI artifact on our side, but we connect to the EAI of OK.Visa.
