### ISSUE TITLE
Task-Service: Release Task-Service in Openshift

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#555]
Release Docker Image
"Deployment"-Configs (Deployment, CM, Secrets, usw.) in allen Umgebungen
Datenbanken bereitstellen (Dev - Test)

Name: "digiwf-task-service"

Version wird von MonoRepo übernommen

Config im API-GW für neue Route

## Akzeptanzkriterium
* Task-Service läuft auf Test/Dev und alles für die weiteren Umgebungen ist so vorbereitet, sodass mit dem nächsten Release es ausgerollt werden kann

## Todos
- [x] Datenbanken bestellen
- [x] Secrets in den Umgebungen einrichten (test, demo, processestest, processesdemo, processeshotfix, p)
- [x] Kafka Topics prüfen / beantragen
- [x] Taskservice für Umgebungen konfigurieren
  - [x] test
  - [x] demo
  - [x] processestest
  - [x] processesdemo
  - [x] processeshotfix
  - [x] p
- [ ] Task Migrationen auf Demo testen

**Comment by darenegade** [comment]
@dominikhorn93 @zambrovski 

Wegen Test-EZLDAP: https://git.muenchen.de/km23/einrichtungsverwaltung/ezLDAP#hosted-api-testumgebungen

**Comment by dominikhorn93** [comment]
Aktueller Stand:
- Datenbanken sind bestellt mit CAP Freischaltung
- Test Deployment ist eingerichtet, aber nicht fertiggestellt (da auf DB gewartet werden muss)

Offen:
- Kafka Topics für P beantragen
- demo, processestest, processesdemo, hotfix bespielen
- Task Migrationen ausführen
  - Client Roles für ssotest und sso beantragen, um den Import triggern zu dürfen
- P Deployment vorbereiten

**Comment by dominikhorn93** [comment]
@zambrovski sehe ich das richtig, dass wir unseren Usern in ssotest und im sso die Role geben müssen, um den Task Import auszuführen?

**Comment by dominikhorn93** [comment]
Habe oben eine Checkliste erstellt und abgehakt was ich gemacht habe.

**Comment by darenegade** [comment]
Hab die Checkliste angepasst. Ziel dieses Tickets war es nicht, den Release auf allen Umgebungen durchzuführen. Es ging immer nur um Vorbereitung aller notwendigen Punkte für den Release (Configs, DBs, Topics usw.). Dann ist hier das Akzeptanzkriterium auch erfüllt und der Rest dann im #564
