### ISSUE TITLE
Deployment of Element Templates

### ISSUE THREAD

**Issue by martind260** [it-at-m/digiwf-project#98]
**Is your feature request related to a problem? Please describe.**
Element Templates frequently change, like Forms and ProcessDefinitions. Such resources should not be coded in the application but modeled via an editor and deployed to the engine/modeler.

**Describe the solution you'd like**

Stage 1
- [ ] Allow to **disable editing** for specific artifact types (upload / **update** / delete / download) 
- [ ] It should be possible to upload a element template file that is recognized as such and then stored in a repository
- [ ] All persisted element templates are presented in the modeler app in the property panel section for ServiceTasks and CallActivities
- [ ] Newly uploaded files overwrite existing ones without versioning
- [ ] Authorization is not needed

_The following steps should not be implemented due to the web-ide epic_

Stage 2
- [ ] You can create a new element template over the "Add" action menu
- [ ] Versioning ability is implemented
- [ ] There is an authorization concept to access and edit repository resources

Stage 3
- [ ] You can edit an element template with an editor supporting syntax highlighting and validation

**Comment by lmoesle** [comment]
Released with Review April 2022.
